version: "3.8"

volumes:
    sonar-plugins:
        external: true
    sonar-data:
        external: true
    sonar-search:
        external: true

services:
    database:
        image: postgres:13.3-alpine
        environment: 
            - POSTGRES_PASSWORD=secret
            - POSTGRES_USER=sonar
        volumes:
            - sonar-data:/var/lib/postgresql/data

    sonar:
        image: sonarqube:8.9-community
        environment: 
            # required by branches plugin to work properly
            - SONAR_WEB_JAVAADDITIONALOPTS=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.8.0.jar=web
            - SONAR_CE_JAVAADDITIONALOPTS=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.8.0.jar=ce
            # common parameters
            - SONAR_TELEMETRY_ENABLE=false
            - SONAR_UPDATECENTER_ACTIVATE=true
            - SONARQUBE_JDBC_URL=jdbc:postgresql://database:5432/postgres
            - SONARQUBE_JDBC_USERNAME=sonar
            - SONARQUBE_JDBC_PASSWORD=secret
        volumes:
            - sonar-plugins:/opt/sonarqube/extensions/plugins
            - sonar-search:/opt/sonarqube/data
        ports: 
            - 9000:9000
        depends_on: 
            - database
